language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - TERM=dumb gradle -q assemble --stacktrace

script:
  - TERM=dumb gradle check --stacktrace

jdk:
  - oraclejdk8
  - oraclejdk7
